# Generated by Django 5.0.3 on 2024-03-13 22:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=50)),
                ('postcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.organization')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='organizations',
            field=models.ManyToManyField(blank=True, null=True, through='event_app.OrganizationEvent', to='event_app.organization'),
        ),
    ]
